{
 "openapi": "3.0.0",
 "info": {
  "title": "Channels API",
  "description": "Для работы с API всегда нужно в заголовках отправлять параметры авторизации: <b>Authorization: Bearer eyJ0eXAiOiJKV1QiLC...</b> Кроме запросов регистрации и получения Token",
  "version": "1.0.0"
 },
 "host": "work.loc",
 "basePath": "/request",
 "tags": [
  {
   "name": "Вакансии",
   "description": "Операции с вакансиями"
  },
  {
   "name": "Категории",
   "description": "Операции с категориями"
  },
  {
   "name": "Компании",
   "description": "Операции с компаниями"
  },
  {
   "name": "Образование",
   "description": "Операции с образованием"
  },
  {
   "name": "Работодатели",
   "description": "Операции с работодателями"
  },
  {
   "name": "Сообщения",
   "description": "Операции с сообщениями"
  },
  {
   "name": "Аттачменты к сообщениями",
   "description": "Операции с аттачментами к сообщениям"
  },
  {
   "name": "Ссылки",
   "description": "Парсинг ссылок на мета теги"
  }
 ],
 "schemes": [
  "http",
  "https"
 ],
 "security": [
  {
   "bearerAuth": []
  }
 ],
 "consumes": [
  "application/json",
  "application/xml"
 ],
 "produces": [
  "application/json",
  "application/xml"
 ],
 "paths": {
  "/request/vacancy": {
   "get": {
    "summary": "Просмотр всех вакансий",
    "description": "Для того что-бы посмотреть вакансию, нужно отпрвавить <br>GET</b> запрос на <b>/request/vacancy</b>.",
    "tags": [
     "Вакансии"
    ],
    "responses": {
     "200": {
      "description": "OK"
     }
    }
   }
  },
  "/request/vacancy/{vacancy_id}": {
   "get": {
    "summary": "Просмотр одной вакансии",
    "description": "Для того что-бы посмотреть вакансию, нужно отпрвавить <br>GET</b> запрос на <b>/request/vacancy/{vacancy_id}</b>. Также существует необязательный параметр <b>expand</b> в который через запятую можно вводить параметры <br> Список параметров: <br> - views0 - информация о просмотрах данной вакансии<br> - countViews - информация о суммарном количестве промотров<br> - company - информация о компании разместившей вакансию<br> - employment_type - информация о виде занятости<br> - vacancy_skill - требуемые навыки<br> - category - категория вакансии<br> - can_update - возможность поднятия вакансии выше в списке",
    "tags": [
     "Вакансии"
    ],
    "parameters": [
     {
      "name": "vacancy_id",
      "in": "path",
      "description": "Vacancy ID",
      "schema": {
       "type": "integer",
       "format": "int64"
      }
     },
     {
      "name": "expand",
      "in": "query",
      "description": "Expand",
      "schema": {
       "type": "string",
       "format": "string"
      }
     }
    ],
    "responses": {
     "200": {
      "description": "OK",
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/Vacancy"
        }
       }
      }
     }
    }
   }
  },
  "/request/vacancy/my-index": {
   "get": {
    "summary": "Просмотр всех вакансий текущего пользователя",
    "description": "Для того что-бы посмотреть вакансию, нужно отпрвавить <br>GET</b> запрос на <b>/request/vacancy/my-index</b>. Также существует необязательный параметр <b>expand</b> в который через запятую можно вводить параметры <br> Список параметров: <br> - views0 - информация о просмотрах данной вакансии<br> - countViews - информация о суммарном количестве промотров<br> - company - информация о компании разместившей вакансию<br> - employment_type - информация о виде занятости<br> - vacancy_skill - требуемые навыки<br> - category - категория вакансии<br> - can_update - возможность поднятия вакансии выше в списке",
    "tags": [
     "Вакансии"
    ],
    "parameters": [
     {
      "name": "expand",
      "in": "query",
      "description": "Expand",
      "schema": {
       "type": "string",
       "format": "string"
      }
     }
    ],
    "responses": {
     "200": {
      "description": "OK",
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/Vacancy"
        }
       }
      }
     }
    }
   }
  },
  "/request/vacancy/create": {
   "post": {
    "summary": "Добавление вакансии",
    "description": "Для того, чтобы добавить новую вакансию, необходимо отправить <b>POST</b> запрос на <b>/request/vacancy/create</b>",
    "tags": [
     "Вакансии"
    ],
    "requestBody": {
     "content": {
      "application/json": {
       "schema": {
        "type": "object",
        "properties": {
         "company_id": {
          "type": "integer",
          "example": ""
         },
         "post": {
          "type": "string",
          "example": ""
         },
         "responsibilities": {
          "type": "string",
          "example": ""
         },
         "min_salary": {
          "type": "integer",
          "example": ""
         },
         "max_salary": {
          "type": "integer",
          "example": ""
         },
         "qualification_requirements": {
          "type": "string",
          "example": ""
         },
         "work_experience": {
          "type": "string",
          "example": ""
         },
         "education": {
          "type": "string",
          "example": ""
         },
         "category": {
          "type": "array",
          "items": {
           "type": "integer"
          }
         },
         "working_conditions": {
          "type": "string",
          "example": ""
         },
         "video": {
          "type": "string",
          "example": ""
         },
         "city": {
          "type": "string",
          "example": ""
         },
         "address": {
          "type": "string",
          "example": ""
         },
         "home_number": {
          "type": "integer",
          "example": ""
         },
         "employment_type_id": {
          "type": "integer",
          "example": ""
         },
         "status": {
          "type": "integer",
          "example": ""
         }
        }
       }
      }
     }
    },
    "responses": {
     "200": {
      "description": "OK",
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/Vacancy_create"
        }
       }
      }
     }
    }
   }
  },
  "/request/vacancy/update": {
   "put": {
    "summary": "Редактирование вакансии",
    "description": "Для того чтобы редактировать вакансию, необходимо отправить <b>PUT</b> запрос на <b>/request/vacancy/update</b>",
    "tags": [
     "Вакансии"
    ],
    "parameters": [
     {
      "name": "id",
      "in": "query",
      "description": "Vacancy_ID",
      "schema": {
       "type": "integer"
      }
     }
    ],
    "requestBody": {
     "content": {
      "application/json": {
       "schema": {
        "type": "object",
        "properties": {
         "company_id": {
          "type": "integer",
          "example": ""
         },
         "post": {
          "type": "string",
          "example": ""
         },
         "responsibilities": {
          "type": "string",
          "example": ""
         },
         "min_salary": {
          "type": "integer",
          "example": ""
         },
         "max_salary": {
          "type": "integer",
          "example": ""
         },
         "qualification_requirements": {
          "type": "string",
          "example": ""
         },
         "work_experience": {
          "type": "string",
          "example": ""
         },
         "education": {
          "type": "string",
          "example": ""
         },
         "category": {
          "type": "array",
          "items": {
           "type": "integer"
          }
         },
         "working_conditions": {
          "type": "string",
          "example": ""
         },
         "video": {
          "type": "string",
          "example": ""
         },
         "city": {
          "type": "string",
          "example": ""
         },
         "address": {
          "type": "string",
          "example": ""
         },
         "home_number": {
          "type": "integer",
          "example": ""
         },
         "employment_type_id": {
          "type": "integer",
          "example": ""
         },
         "status": {
          "type": "integer",
          "example": ""
         }
        }
       }
      }
     }
    },
    "responses": {
     "200": {
      "description": "OK",
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/Vacancy_create"
        }
       }
      }
     }
    }
   }
  },
  "/request/vacancy/delete": {
   "delete": {
    "summary": "Удаление  вакансии",
    "description": "Для того, чтобы удалить вакансию, необходимо отправить <b>DELETE</b> запрос на <b>/request/vacancy/delete</b>",
    "tags": [
     "Вакансии"
    ],
    "parameters": [
     {
      "name": "id",
      "in": "query",
      "description": "Vacancy_ID",
      "schema": {
       "type": "integer",
       "format": "integer"
      }
     }
    ],
    "responses": {
     "200": {
      "description": "OK"
     }
    }
   }
  },
  "/request/category": {
   "get": {
    "summary": "Просмотр всех категорий",
    "description": "Для того, чтобы посмотреть все категории, необходимо отправить <b>GET</b> запрос на <b>/request/category</b>.",
    "tags": [
     "Категории"
    ],
    "responses": {
     "200": {
      "description": "OK"
     }
    }
   }
  },
  "/request/category/{category_id}": {
   "get": {
    "summary": "Просмотр одной категории",
    "description": "Для того, чтобы посмотреть конкретную категорию, необходимо отправить <b>GET</b> запрос на <b>/request/category/{category_id}</b>.",
    "tags": [
     "Категории"
    ],
    "parameters": [
     {
      "name": "category_id",
      "in": "path",
      "description": "Category ID",
      "schema": {
       "type": "integer",
       "format": "int64"
      }
     }
    ],
    "responses": {
     "200": {
      "description": "OK"
     }
    }
   }
  },
  "/request/company/": {
   "get": {
    "summary": "Просмотр всех компаний",
    "description": "Для того, чтобы посмотреть все компании, необходимо отправить <b>GET</b> запрос на <b>/request/company</b>.",
    "tags": [
     "Компании"
    ],
    "responses": {
     "200": {
      "description": "OK",
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/Company"
        }
       }
      }
     }
    }
   }
  },
  "/request/company/{company_id}": {
   "get": {
    "summary": "Просмотр одной компании",
    "description": "Для того, чтобы посмотреть конкретную компанию, необходимо отправить <b>GET</b> запрос на <b>/request/company/{company_id}</b>.",
    "tags": [
     "Компании"
    ],
    "parameters": [
     {
      "name": "company_id",
      "in": "path",
      "description": "Vacancy ID",
      "schema": {
       "type": "integer",
       "format": "int64"
      }
     }
    ],
    "responses": {
     "200": {
      "description": "OK",
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/Company"
        }
       }
      }
     }
    }
   }
  },
  "/request/company/my-index": {
   "get": {
    "summary": "Просмотр всех компаний текущего пользователя",
    "description": "Для того что-бы посмотреть вакансию, нужно отпрвавить <br>GET</b> запрос на <b>/request/vacancy/my-index</b>.",
    "tags": [
     "Компании"
    ],
    "responses": {
     "200": {
      "description": "OK",
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/Company"
        }
       }
      }
     }
    }
   }
  },
  "/request/company/create": {
   "post": {
    "summary": "Добавление компании",
    "description": "Для того, чтобы добавить новую компанию, необходимо отправить <b>POST</b> запрос на <b>/request/company/create</b>",
    "tags": [
     "Компании"
    ],
    "requestBody": {
     "content": {
      "application/json": {
       "schema": {
        "type": "object",
        "properties": {
         "user_id": {
          "type": "integer",
          "example": ""
         },
         "name": {
          "type": "string",
          "example": ""
         },
         "image": {
          "type": "string",
          "example": ""
         },
         "website": {
          "type": "string",
          "example": ""
         },
         "activity_field": {
          "type": "string",
          "example": ""
         },
         "vk": {
          "type": "string",
          "example": ""
         },
         "facebook": {
          "type": "string",
          "example": ""
         },
         "instagram": {
          "type": "string",
          "example": ""
         },
         "skype": {
          "type": "string",
          "example": ""
         },
         "description": {
          "type": "string",
          "example": ""
         },
         "contact_person": {
          "type": "string",
          "example": ""
         },
         "status": {
          "type": "integer",
          "example": ""
         },
         "phone": {
          "type": "string",
          "example": ""
         }
        }
       }
      }
     }
    },
    "responses": {
     "200": {
      "description": "OK",
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/Company_create"
        }
       }
      }
     }
    }
   }
  },
  "/request/company/{companyID}": {
   "put": {
    "summary": "Редактирование компании",
    "description": "Для того чтобы редактировать компанию, необходимо отправить <b>PUT</b> запрос на <b>/request/company/update</b>",
    "tags": [
     "Компании"
    ],
    "parameters": [
     {
      "name": "companyID",
      "in": "path",
      "description": "Company_ID",
      "schema": {
       "type": "integer"
      }
     }
    ],
    "requestBody": {
     "content": {
      "application/json": {
       "schema": {
        "type": "object",
        "properties": {
         "user_id": {
          "type": "integer",
          "example": ""
         },
         "name": {
          "type": "string",
          "example": ""
         },
         "image": {
          "type": "object",
          "properties": {
           "changeImg": {
            "type": "string",
            "example": "false"
           }
          }
         },
         "website": {
          "type": "string",
          "example": ""
         },
         "activity_field": {
          "type": "string",
          "example": ""
         },
         "vk": {
          "type": "string",
          "example": ""
         },
         "facebook": {
          "type": "string",
          "example": ""
         },
         "instagram": {
          "type": "string",
          "example": ""
         },
         "skype": {
          "type": "string",
          "example": ""
         },
         "description": {
          "type": "string",
          "example": ""
         },
         "contact_person": {
          "type": "string",
          "example": ""
         },
         "status": {
          "type": "integer",
          "example": ""
         },
         "phone": {
          "type": "string",
          "example": ""
         }
        }
       }
      }
     }
    },
    "responses": {
     "200": {
      "description": "OK",
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/Company_create"
        }
       }
      }
     }
    }
   }
  },
  "/request/company/{companyDeletedID}": {
   "delete": {
    "summary": "Удаление компании",
    "description": "Для того, чтобы удалить вакансию, необходимо отправить <b>DELETE</b> запрос на <b>/request/company</b>",
    "tags": [
     "Компании"
    ],
    "parameters": [
     {
      "name": "companyDeletedID",
      "in": "path",
      "description": "Company_ID",
      "schema": {
       "type": "integer",
       "format": "integer"
      }
     }
    ],
    "responses": {
     "200": {
      "description": "OK"
     }
    }
   }
  },
  "/request/education": {
   "get": {
    "summary": "Получение списка образований",
    "description": "Для получения списка образований необходимо отправить <b>GET</b> запрос на <b>/request/education</b>. Также существует необязательный параметр <b>expand</b>, в который можно передать параметр <b>resume</b> и получить резюме к которому привязан данный лист образования",
    "tags": [
     "Образование"
    ],
    "parameters": [
     {
      "name": "expand",
      "in": "query",
      "description": "Expand",
      "schema": {
       "type": "string",
       "format": "string"
      }
     }
    ],
    "responses": {
     "200": {
      "description": "OK",
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/Education"
        }
       }
      }
     }
    }
   }
  },
  "/request/education/{education_id}": {
   "get": {
    "summary": "Получение одного бланка образования",
    "description": "Для того, чтобы посмотреть конкретное образование, необходимо отправить <b>GET</b> запрос на <b>/request/education/{education_id}</b>. Также существует необязательный параметр <b>expand</b>, в который можно передать параметр <b>resume</b> и получить резюме к которому привязан данный лист образования",
    "tags": [
     "Образование"
    ],
    "parameters": [
     {
      "name": "education_id",
      "in": "path",
      "description": "Vacancy ID",
      "schema": {
       "type": "integer",
       "format": "int64"
      }
     },
     {
      "name": "expand",
      "in": "query",
      "description": "Expand",
      "schema": {
       "type": "string",
       "format": "string"
      }
     }
    ],
    "responses": {
     "200": {
      "description": "OK",
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/Education"
        }
       }
      }
     }
    }
   }
  },
  "/request/employer": {
   "get": {
    "summary": "Просмотр всех работодателей",
    "description": "Для того, чтобы посмотреть всех работодателей, необходимо отправить <b>GET</b> запрос на <b>/request/employer</b>.",
    "tags": [
     "Работодатели"
    ],
    "responses": {
     "200": {
      "description": "OK",
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/Employer"
        }
       }
      }
     }
    }
   }
  }
 },
 "components": {
  "securitySchemes": {
   "bearerAuth": {
    "type": "http",
    "scheme": "bearer",
    "bearerFormat": "JWT"
   }
  },
  "schemas": {
   "Employer": {
    "type": "object",
    "properties": {
     "id": {
      "type": "integer",
      "description": "ID работодателя"
     },
     "user_id": {
      "type": "integer",
      "description": "ID пользователя"
     },
     "first_name": {
      "type": "string",
      "description": "Имя"
     },
     "second_name": {
      "type": "string",
      "description": "Фамилия"
     },
     "birth_date": {
      "type": "date",
      "description": "Дата рождения"
     },
     "status": {
      "type": "integer",
      "description": "Статус 1 - активен, 0 - неактивен"
     },
     "created_at": {
      "type": "integer",
      "description": "Дата создания"
     },
     "updated_at": {
      "type": "integer",
      "description": "Дата редактирования"
     },
     "owner": {
      "type": "integer",
      "description": "ID создателя"
     }
    },
    "example": {
     "id": 9,
     "user_id": 38,
     "first_name": "Дмитрий",
     "second_name": "Завадский",
     "birth_date": "2017-01-16T00:00:00.000Z",
     "status": 1,
     "created_at": "17-01-2019",
     "updated_at": 1560257714,
     "owner": 1
    }
   },
   "Education": {
    "type": "object",
    "properties": {
     "id": {
      "type": "integer",
      "description": "ID бланка с образованием"
     },
     "resume_id": {
      "type": "integer",
      "description": "ID резюме с текущим образованием"
     },
     "name": {
      "type": "string",
      "description": "Название университета"
     },
     "faculty": {
      "type": "string",
      "description": "Название факультета"
     },
     "year_from": {
      "type": "integer",
      "description": "Дата начала обучения"
     },
     "year_to": {
      "type": "integer",
      "description": "Дата начала обучения"
     },
     "academic_degree": {
      "type": "string",
      "description": "Академическая степень"
     },
     "specialization": {
      "type": "string",
      "description": "Специализация"
     },
     "status": {
      "type": "integer",
      "description": "Статус 1 - активен, 0 - неактивен"
     },
     "created_at": {
      "type": "integer",
      "description": "Дата создания"
     },
     "updated_at": {
      "type": "integer",
      "description": "Дата редактирования"
     },
     "owner": {
      "type": "integer",
      "description": "ID создателя"
     }
    },
    "example": {
     "id": 9,
     "resume_id": 38,
     "name": "ДОННТУ",
     "faculty": "ФКНТ",
     "year_from": 2015,
     "year_to": 2019,
     "academic_degree": "Бакалавр",
     "specialization": "ПОВТ",
     "status": 1,
     "created_at": 1555514942,
     "updated_at": 1559211173,
     "owner": null
    }
   },
   "Company_create": {
    "type": "object",
    "properties": {
     "user_id": {
      "type": "integer",
      "description": "ID пользователя"
     },
     "name": {
      "type": "string",
      "description": "Титульное название"
     },
     "image": {
      "type": "string",
      "description": "Ссылка на картинку"
     },
     "website": {
      "type": "string",
      "description": "Ссылка на сайт компании"
     },
     "activity_field": {
      "type": "string",
      "description": "Сфера деятельности компании"
     },
     "vk": {
      "type": "string",
      "description": "Ссылка на группу во Вконтакте"
     },
     "facebook": {
      "type": "string",
      "description": "Ссылка на группа на Facebook"
     },
     "instagram": {
      "type": "string",
      "description": "Ссылка на профиль в Instagram"
     },
     "skype": {
      "type": "string",
      "description": "Рабочий skype компании"
     },
     "description": {
      "type": "string",
      "description": "Информация о компании"
     },
     "contact_person": {
      "type": "string",
      "description": "Контактное лицо"
     },
     "status": {
      "type": "integer",
      "description": "Статус 1 - активен, 0 - неактивен"
     },
     "phone": {
      "type": "string",
      "description": "Контактный номер телефона"
     }
    },
    "example": {
     "user_id": 39,
     "name": "Craft-Group",
     "image": "https://rabota.today/media/company/42/4b/cac45896eecd8b4152abada18e8c.png",
     "website": "https://web-artcraft.com/",
     "activity_field": "Разработка сайтов",
     "vk": "https://vk.com/web_craft_group",
     "facebook": "https://www.facebook.com/groups/2071589713151084/",
     "instagram": "https://www.instagram.com/explore/tags/craft-group/",
     "skype": "craftgroup459",
     "description": "Молодая и дружная команда занимающаяся разработкой сайтов",
     "contact_person": "Дмитрий Завадский",
     "status": 1,
     "phone": 380714086945
    }
   },
   "Vacancy_create": {
    "type": "object",
    "properties": {
     "company_id": {
      "type": "integer",
      "description": "ID компании разместившей вакансию"
     },
     "post": {
      "type": "string",
      "description": "Титульное название"
     },
     "responsibilities": {
      "type": "string",
      "description": "Обязанности"
     },
     "min_salary": {
      "type": "integer",
      "description": "Минимальная зарплата"
     },
     "max_salary": {
      "type": "integer",
      "description": "Максимальная зарплата"
     },
     "qualification_requirements": {
      "type": "string",
      "description": "Квалификационные требования"
     },
     "work_experience": {
      "type": "integer",
      "description": "Требуемый опыт работы"
     },
     "education": {
      "type": "string",
      "description": "Образование"
     },
     "working_conditions": {
      "type": "string",
      "description": "Условия труда"
     },
     "video": {
      "type": "string",
      "description": "Видео о вакансии"
     },
     "city": {
      "type": "string",
      "description": "Город"
     },
     "address": {
      "type": "string",
      "description": "Аддрес"
     },
     "home_number": {
      "type": "string",
      "description": "Номер дома"
     },
     "employment_type_id": {
      "type": "integer",
      "description": "Тип работы"
     },
     "views": {
      "type": "integer",
      "description": "Количество просмотров"
     },
     "status": {
      "type": "integer",
      "description": "Статус"
     }
    },
    "example": {
     "company_id": 18,
     "post": "PHP Разработчик",
     "responsibilities": "Разработка сайтов",
     "min_salary": 15000,
     "max_salary": 30000,
     "qualification_requirements": "PHP, JS, HTML/CSS",
     "work_experience": 1,
     "education": "Не требуется",
     "category": [
      1,
      2
     ],
     "working_conditions": "8 часов в день/5 дней в неделю",
     "video": "Ссылка на видео",
     "city": "Донецк",
     "address": "бул. Пушкина",
     "home_number": 128,
     "employment_type_id": 3,
     "status": 1
    }
   },
   "Vacancy": {
    "type": "object",
    "properties": {
     "id": {
      "type": "integer",
      "description": "ID вакансии"
     },
     "company_id": {
      "type": "integer",
      "description": "ID компании разместившей вакансию"
     },
     "post": {
      "type": "string",
      "description": "Титульное название"
     },
     "responsibilities": {
      "type": "string",
      "description": "Обязанности"
     },
     "min_salary": {
      "type": "integer",
      "description": "Минимальная зарплата"
     },
     "max_salary": {
      "type": "integer",
      "description": "Максимальная зарплата"
     },
     "qualification_requirements": {
      "type": "string",
      "description": "Квалификационные требования"
     },
     "work_experience": {
      "type": "integer",
      "description": "Требуемый опыт работы"
     },
     "education": {
      "type": "string",
      "description": "Образование"
     },
     "working_conditions": {
      "type": "string",
      "description": "Условия труда"
     },
     "video": {
      "type": "string",
      "description": "Видео о вакансии"
     },
     "city": {
      "type": "string",
      "description": "Город"
     },
     "address": {
      "type": "string",
      "description": "Аддрес"
     },
     "home_number": {
      "type": "string",
      "description": "Номер дома"
     },
     "employment_type_id": {
      "type": "integer",
      "description": "Тип работы"
     },
     "views": {
      "type": "integer",
      "description": "Количество просмотров"
     },
     "status": {
      "type": "integer",
      "description": "Статус"
     },
     "created_at": {
      "type": "integer",
      "description": "Дата создания"
     },
     "updated_at": {
      "type": "integer",
      "description": "Дата редактирования"
     },
     "owner": {
      "type": "integer",
      "description": "Количество владельцев"
     },
     "update_time": {
      "type": "integer",
      "description": "Время поднятия"
     }
    },
    "example": {
     "id": 5,
     "company_id": 1,
     "post": "PHP Developer",
     "responsibilities": "Разработка сайтов",
     "min_salary": 15000,
     "max_salary": 30000,
     "qualification_requirements": "PHP, JS, HTML/CSS",
     "work_experience": "От 1 года",
     "education": "Не требуется",
     "working_conditions": "8 часов в день/5 дней в неделю",
     "video": "Ссылка на видео",
     "city": "Донецк",
     "address": "бул. Пушкина",
     "home_number": 128,
     "employment_type_id": 3,
     "views": 148,
     "status": 1,
     "created_at": 1555327833,
     "updated_at": 1565008907,
     "owner": 4,
     "update_time": null
    }
   },
   "Company": {
    "type": "object",
    "properties": {
     "id": {
      "type": "integer",
      "description": "ID компании"
     },
     "user_id": {
      "type": "integer",
      "description": "ID компании"
     },
     "name": {
      "type": "string",
      "description": "Название компании"
     },
     "image_url": {
      "type": "string",
      "description": "Адрес картинки"
     },
     "website": {
      "type": "string",
      "description": "Сайт компании"
     },
     "activity_field": {
      "type": "string",
      "description": "Сфера деятельности"
     },
     "vk": {
      "type": "string",
      "description": "Ссылка на группу или страницу ВК"
     },
     "facebook": {
      "type": "string",
      "description": "Ссылка на группу или страницу facebook"
     },
     "instagram": {
      "type": "string",
      "description": "Ссылка на инстаграмм профиль компании"
     },
     "skype": {
      "type": "string",
      "description": "Skype компании"
     },
     "description": {
      "type": "string",
      "description": "Информация о компании"
     },
     "contact_person": {
      "type": "string",
      "description": "Контактное лицо"
     },
     "status": {
      "type": "integer",
      "description": "Статус 1 - активно, 0 - неактивно"
     },
     "created_at": {
      "type": "integer",
      "description": "дата создания"
     },
     "updated_at": {
      "type": "integer",
      "description": "дата последнего редактирования"
     },
     "owner": {
      "type": "integer",
      "description": "ID владельца"
     }
    },
    "example": {
     "id": 18,
     "user_id": 39,
     "name": "Craft-Group",
     "image_url": "https://rabota.today/media/company/42/4b/cac45896eecd8b4152abada18e8c.png",
     "website": "https://web-artcraft.com/",
     "activity_field": "Разработка сайтов",
     "vk": "https://vk.com/web_craft_group",
     "facebook": "https://www.facebook.com/groups/2071589713151084/",
     "instagram": "https://www.instagram.com/explore/tags/craft-group/",
     "skype": "craftgroup459",
     "description": "Молодая и дружная команда занимающаяся разработкой сайтов",
     "contact_person": "Дмитрий Завадский",
     "status": 1,
     "created_at": 1563460316,
     "updated_at": 1563460316,
     "owner": 39
    }
   },
   "RegistrationForm": {
    "type": "object",
    "properties": {
     "username": {
      "type": "string",
      "description": "Отображаемое имя на сайте"
     },
     "password": {
      "type": "string",
      "description": "Пароль пользователя"
     },
     "password_confirmation": {
      "type": "string",
      "description": "Подтверждение пароля пользователя"
     },
     "email": {
      "type": "string",
      "format": "email",
      "description": "Email, указанный при регистрации"
     }
    },
    "required": [
     "username",
     "password",
     "password_confirmation",
     "email"
    ],
    "example": {
     "username": "Jessica Smith",
     "password": "1234qwer",
     "password_confirmation": "1234qwer",
     "email": "jessica@gmail.com"
    },
    "xml": {
     "name": "RegistrationForm"
    }
   },
   "LoginForm": {
    "type": "object",
    "properties": {
     "grant_type": {
      "type": "string",
      "enum": [
       "password",
       "refresh_token"
      ],
      "default": "password",
      "description": "Тип запроса токена"
     },
     "client_id": {
      "type": "integer",
      "description": "Идентификатор клиента (генерируется по запросу)"
     },
     "client_secret": {
      "type": "string",
      "description": "Ключ клиента (генерируется по запросу)"
     },
     "username": {
      "type": "string",
      "format": "email",
      "description": "Email пользователя"
     },
     "password": {
      "type": "string",
      "description": "Пароль пользователя"
     },
     "refresh_token": {
      "type": "string",
      "description": "refresh token полученый при авторизации"
     },
     "scope": {
      "type": "string"
     }
    },
    "required": [
     "grant_type",
     "client_id",
     "client_secret"
    ],
    "example": {
     "grant_type": "password",
     "client_id": 1,
     "client_secret": "HJnYUlzOSXOxoIc15HMlxUJb1SNzaeYKn0tSMBls",
     "username": "jessica@gmail.com",
     "password": "1234qwer",
     "refresh_token": "oIc15HMlxUJb1SNzaeYKn0tSMBls..."
    }
   },
   "xml": {
    "name": "LoginForm"
   },
   "User": {
    "type": "object",
    "properties": {
     "username": {
      "type": "string",
      "description": "Отображаемое имя на сайте",
      "example": "Jessica Smith"
     },
     "password": {
      "type": "string",
      "description": "Пароль пользователя",
      "password": "1234qwer"
     },
     "password_confirmation": {
      "type": "string",
      "description": "Подтверждение пароля пользователя",
      "password_confirmation": "1234qwer"
     },
     "email": {
      "type": "string",
      "format": "email",
      "description": "Email, указанный при регистрации",
      "email": "jessica@gmail.com"
     },
     "avatar": {
      "$ref": "#/components/schemas/Avatar"
     }
    },
    "required": [
     "username",
     "password",
     "password_confirmation",
     "email"
    ],
    "xml": {
     "name": "User"
    }
   },
   "Avatar": {
    "type": "object",
    "properties": {
     "avatar_id": {
      "type": "integer",
      "format": "int64",
      "description": "Avatar ID"
     },
     "origin": {
      "type": "string",
      "description": "Ссылка на аватарку"
     },
     "average": {
      "type": "string",
      "description": "Ссылка на аватарку среднего размера"
     },
     "small": {
      "type": "string",
      "description": "Ссылка на аватарку уменьшенного размера"
     },
     "status": {
      "type": "string",
      "enum": [
       "active",
       "disable"
      ]
     }
    },
    "example": {
     "origin": "http://files.newchannels.loc/img/channel/0/04/04882234d9761dc7072283ba61e2c29b.jpg",
     "average": "http://files.newchannels.loc/img/channel/0/04/04882234d9761dc7072283ba61e2c29b_400.jpg",
     "small": "http://files.newchannels.loc/img/channel/0/04/04882234d9761dc7072283ba61e2c29b_150.jpg"
    },
    "xml": {
     "name": "Avatar"
    }
   },
   "Group": {
    "type": "object",
    "properties": {
     "title": {
      "type": "string",
      "description": "Название группы"
     },
     "slug": {
      "type": "integer",
      "format": "int64",
      "description": "URL группы"
     },
     "status": {
      "type": "string",
      "enum": [
       "active",
       "disable"
      ],
      "default": "active",
      "description": "Статус группы (active / disable)"
     },
     "owner_id": {
      "type": "integer",
      "format": "int64",
      "description": "Идентификатор создателя группы"
     },
     "avatar": {
      "type": "integer",
      "format": "int64",
      "allowEmpty": true
     }
    },
    "required": [
     "title",
     "slug",
     "status",
     "owner_id"
    ],
    "xml": {
     "name": "Group"
    }
   },
   "Channel": {
    "type": "object",
    "properties": {
     "channel_id": {
      "type": "integer",
      "format": "int64",
      "example": 6
     },
     "title": {
      "type": "string",
      "example": "Mr."
     },
     "slug": {
      "type": "string",
      "example": "mr"
     },
     "status": {
      "type": "string",
      "enum": [
       "active",
       "disable"
      ],
      "default": "active",
      "example": "active"
     },
     "type": {
      "type": "string",
      "enum": [
       "chat",
       "wall"
      ],
      "default": "chat",
      "example": "chat"
     },
     "private": {
      "type": "integer",
      "enum": [
       0,
       1
      ],
      "default": 1,
      "example": 1
     },
     "owner_id": {
      "type": "integer",
      "format": "int64",
      "example": 2
     },
     "user_count": {
      "type": "integer",
      "format": "int64",
      "example": 3
     },
     "avatar": {
      "type": "array",
      "items": {
       "type": "integer"
      },
      "minItems": 1
     }
    },
    "xml": {
     "name": "Channel"
    }
   },
   "Link": {
    "type": "object",
    "properties": {
     "url": {
      "type": "string",
      "description": "URL сайта",
      "example": "https://laravel.com/"
     },
     "title": {
      "type": "string",
      "description": "Заголовок сайта",
      "example": "Laravel - The PHP Framework For Web Artisans"
     },
     "description": {
      "type": "string",
      "description": "Описание сайта",
      "example": "Laravel - The PHP framework for web artisans"
     },
     "icon": {
      "type": "string",
      "description": "Лого сайта",
      "example": "/assets/img/laravel-logo-white.png"
     },
     "base": {
      "type": "string",
      "description": "Доменное имя сайта",
      "example": "laravel.com"
     }
    },
    "xml": {
     "name": "Link"
    }
   }
  }
 }
}